// File generated by FlutterFire CLI.

// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

///

/// Example:

/// ```dart

/// import 'firebase_options.dart';

/// // ...

/// await Firebase.initializeApp(

///   options: DefaultFirebaseOptions.currentPlatform,

/// );

/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjnDGQemhkrivhAEPkAw2LXV3lSxRJf3I',
    appId: '1:372943485559:web:0960793cc2eba203386472',
    messagingSenderId: '372943485559',
    projectId: 'condohubtcc',
    authDomain: 'condohubtcc.firebaseapp.com',
    storageBucket: 'condohubtcc.firebasestorage.app',
    measurementId: 'G-F807XSJSDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQF1hE6QWwHjZMCb9z44ufyEHtvutWAbA',
    appId: '1:372943485559:android:4c8d7ea99c066196386472',
    messagingSenderId: '372943485559',
    projectId: 'condohubtcc',
    storageBucket: 'condohubtcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEr9brgdw7UnTs6pG1hJi03KcwJm19GJ4',
    appId: '1:372943485559:ios:c5cb3b69149efdbc386472',
    messagingSenderId: '372943485559',
    projectId: 'condohubtcc',
    storageBucket: 'condohubtcc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEr9brgdw7UnTs6pG1hJi03KcwJm19GJ4',
    appId: '1:372943485559:ios:c5cb3b69149efdbc386472',
    messagingSenderId: '372943485559',
    projectId: 'condohubtcc',
    storageBucket: 'condohubtcc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjnDGQemhkrivhAEPkAw2LXV3lSxRJf3I',
    appId: '1:372943485559:web:773666bebdf58ed4386472',
    messagingSenderId: '372943485559',
    projectId: 'condohubtcc',
    authDomain: 'condohubtcc.firebaseapp.com',
    storageBucket: 'condohubtcc.firebasestorage.app',
    measurementId: 'G-VEPJQE526F',
  );
}
